added Giskard-deployment
Giskard-AI/giskard-examples pull request #8
Opened 2022-12-08 15:19 UTC by rabah-khalek

Read

2023-01-16 13:40 UTC, Googleton commented on .github/workflows/deployment.yml
> +      - '.github/workflows/deployment.yml'
Should a change on `data.csv` also trigger the workflow?

2023-01-16 13:40 UTC, Googleton commented on Giskard-deployment/Giskard_test.py
> +    PASSED = passed_tests_cnt/len(test_result)*1. > 0.5
Maybe add a comment explaining that "PASSED" for this script is dependent on >50% of tests passing, and that it depends on the use case and tests of the user ? 
From my own experience, in CI/CD there is usually no tolerance for failure

2023-01-16 14:16 UTC, rabah-khalek commented on Giskard-deployment/Giskard_test.py
> +    PASSED = passed_tests_cnt/len(test_result)*1. > 0.5
Yes indeed, that's just an example of a simple rule that can be implemented. In fact, in a realistic deployment, it doesn't make much more sense. I'll add a comment, and also an explanation in the README.

2023-01-24 15:06 UTC, Googleton commented on .github/workflows/auto-comment.yml
> +      - 'data.csv'
After testing, these paths (for train, giskard_test and data) should include the entire path, so
`train.py` => `Giskard-deployment\train.py` etc...

2023-01-24 15:06 UTC, Googleton commented on Giskard-deployment/Giskard_test.py
> +    url = "http://dev.giskard.ai" #if Giskard is installed locally (for installation, see: https://docs.giskard.ai/start/guides/installation)
URL should be an env variable

2023-02-12 22:17 UTC, Googleton requested changes
One last minor nitpick but otherwise good for me!

2023-02-12 22:17 UTC, Googleton commented on .github/workflows/auto-comment.yml
> +      - 'data.csv'
Auto comment workflow file paths aren't absolute, which won't make it function properly

2023-02-12 22:29 UTC, rabah-khalek commented on .github/workflows/auto-comment.yml
> +      - 'data.csv'
Done. Thanks!

2023-02-13 11:34 UTC, andreybavt requested changes

2023-02-13 11:34 UTC, andreybavt commented on .github/workflows/auto-comment.yml
> +      - 'Giskard-deployment/Giskard_test.py'
Should we just track changes in the whole `Giskard-deployment/**` directory?

2023-02-13 11:34 UTC, andreybavt commented on Giskard-deployment/old_deployed_models/08-12-2022_16.35.01/Giskard_tests.json
> +[
What's the reason for pushing test execution results to git? Typically test execution results are linked to the CI/CD pipeline execution results but are not part of the source code

2023-02-13 11:36 UTC, rabah-khalek commented on .github/workflows/auto-comment.yml
> +      - 'Giskard-deployment/Giskard_test.py'
This is currently the auto-message: https://github.com/Giskard-AI/giskard-examples/pull/8#issuecomment-1342892291. It's relevant in the context of a new deployed model. I thought that if the user updated something else in his PR, this message shouldn't show up.

2023-02-13 11:38 UTC, rabah-khalek commented on Giskard-deployment/old_deployed_models/08-12-2022_16.35.01/Giskard_tests.json
> +[
It's just for extra info. The history of why the model was deployed, in case someone would want to revisit the tests.

2023-02-27 09:30 UTC, merged